# Generated by scripts/gen-dsp-library-bindings.mjs. Do not edit.
from typing import Literal, TypeAlias, TypedDict

from ._base import Effect

EffectChannel: TypeAlias = Literal["all", "stereo", "left", "right", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "34", "56", "78", "910", "1112", "1314", "1516"]

class IRReverbAssets(TypedDict):
    impulseResponse: str

EFFECT_METADATA: dict[str, object]
_EFFECT_IMPLEMENTATION: dict[str, dict[str, object]]

class AnalogMeter(Effect):
    effect_type: Literal["AnalogMeter"]
    def __init__(
        self,
        *,
        mode: Literal["VU", "PPM", "RMS", "Sample Peak", "True Peak", "Loudness"] = ...,
        integration: float = ...,
        attack: float = ...,
        release: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class ChromaSpiral(Effect):
    effect_type: Literal["ChromaSpiral"]
    def __init__(
        self,
        *,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class LevelMeter(Effect):
    effect_type: Literal["LevelMeter"]
    def __init__(
        self,
        *,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class NoteSpectrogram(Effect):
    effect_type: Literal["NoteSpectrogram"]
    def __init__(
        self,
        *,
        minimum_midi: int = ...,
        maximum_midi: int = ...,
        regular_candidates: int = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class Oscilloscope(Effect):
    effect_type: Literal["Oscilloscope"]
    def __init__(
        self,
        *,
        display_time: float = ...,
        trigger_mode: Literal["Auto", "Normal", "Off"] = ...,
        trigger_level: float = ...,
        trigger_edge: Literal["Rising", "Falling"] = ...,
        holdoff: float = ...,
        display_level: float = ...,
        vertical_offset: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class PitchMeter(Effect):
    effect_type: Literal["PitchMeter"]
    def __init__(
        self,
        *,
        reference_a4: float = ...,
        minimum_midi: int = ...,
        maximum_midi: int = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class RhythmAnalyzer(Effect):
    effect_type: Literal["RhythmAnalyzer"]
    def __init__(
        self,
        *,
        minimum_bpm: float = ...,
        maximum_bpm: float = ...,
        metronome_click: bool = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class Spectrogram(Effect):
    effect_type: Literal["Spectrogram"]
    def __init__(
        self,
        *,
        d_brange: float = ...,
        points: int = ...,
        high_quality_log: bool = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class SpectrumAnalyzer(Effect):
    effect_type: Literal["SpectrumAnalyzer"]
    def __init__(
        self,
        *,
        d_brange: float = ...,
        points: int = ...,
        high_quality_log: bool = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class StereoMeter(Effect):
    effect_type: Literal["StereoMeter"]
    def __init__(
        self,
        *,
        window_time: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class BassManagement(Effect):
    effect_type: Literal["BassManagement"]
    def __init__(
        self,
        *,
        phase: Literal["IIR", "Linear"] = ...,
        taps: Literal["8192", "16384", "32768"] = ...,
        roles: tuple[int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int] = ...,
        frequencies: tuple[float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float] = ...,
        slopes: tuple[Literal[24, 48, 96], Literal[24, 48, 96], Literal[24, 48, 96], Literal[24, 48, 96], Literal[24, 48, 96], Literal[24, 48, 96], Literal[24, 48, 96], Literal[24, 48, 96], Literal[24, 48, 96], Literal[24, 48, 96], Literal[24, 48, 96], Literal[24, 48, 96], Literal[24, 48, 96], Literal[24, 48, 96], Literal[24, 48, 96], Literal[24, 48, 96]] = ...,
        routes: tuple[int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int] = ...,
        subs: int = ...,
        lfe_frequency: float = ...,
        lfe_slope: Literal[24, 48, 96] = ...,
        lfe_lowpass: bool = ...,
        bass_gain: float = ...,
        lfe_gain: float = ...,
        headroom: float = ...,
        route_inversions: tuple[int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int] = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
        assets: IRReverbAssets | None = ...,
    ) -> None: ...

class ChannelDivider(Effect):
    effect_type: Literal["ChannelDivider"]
    def __init__(
        self,
        *,
        band_count: int = ...,
        frequency1: float = ...,
        slope1: int = ...,
        frequency2: float = ...,
        slope2: int = ...,
        frequency3: float = ...,
        slope3: int = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class DCOffset(Effect):
    effect_type: Literal["DCOffset"]
    def __init__(
        self,
        *,
        offset: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class FIRCrossover(Effect):
    effect_type: Literal["FIRCrossover"]
    def __init__(
        self,
        *,
        latency_mode: Literal["0", "128", "256", "512", "1024"] = ...,
        filter_delay_samples: int = ...,
        band_count: int = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
        assets: IRReverbAssets,
    ) -> None: ...

class Matrix(Effect):
    effect_type: Literal["Matrix"]
    def __init__(
        self,
        *,
        matrix_routes: str = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class MultiChannelPanel(Effect):
    effect_type: Literal["MultiChannelPanel"]
    def __init__(
        self,
        *,
        mute: tuple[bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool] = ...,
        solo: tuple[bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool] = ...,
        volume: tuple[float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float] = ...,
        delay: tuple[float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float] = ...,
        link: tuple[bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool] = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class Mute(Effect):
    effect_type: Literal["Mute"]
    def __init__(
        self,
        *,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class PolarityInversion(Effect):
    effect_type: Literal["PolarityInversion"]
    def __init__(
        self,
        *,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class StereoBalance(Effect):
    effect_type: Literal["StereoBalance"]
    def __init__(
        self,
        *,
        balance: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class Volume(Effect):
    effect_type: Literal["Volume"]
    def __init__(
        self,
        *,
        volume: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class Delay(Effect):
    effect_type: Literal["Delay"]
    def __init__(
        self,
        *,
        pre_delay: float = ...,
        delay_size: float = ...,
        damping: float = ...,
        high_damp: float = ...,
        low_damp: float = ...,
        mix: float = ...,
        feedback: float = ...,
        ping_pong: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class TimeAlignment(Effect):
    effect_type: Literal["TimeAlignment"]
    def __init__(
        self,
        *,
        delay: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class AttackTonalBalance(Effect):
    effect_type: Literal["AttackTonalBalance"]
    def __init__(
        self,
        *,
        attack: float = ...,
        tonal: float = ...,
        attack_enabled: bool = ...,
        tonal_enabled: bool = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class AutoLeveler(Effect):
    effect_type: Literal["AutoLeveler"]
    def __init__(
        self,
        *,
        target_lufs: float = ...,
        time_window: float = ...,
        max_gain: float = ...,
        min_gain: float = ...,
        attack: float = ...,
        release: float = ...,
        noise_gate: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class BrickwallLimiter(Effect):
    effect_type: Literal["BrickwallLimiter"]
    def __init__(
        self,
        *,
        threshold: float = ...,
        release: float = ...,
        lookahead: float = ...,
        oversampling: Literal[1, 2, 4, 8] = ...,
        input_gain: float = ...,
        margin: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class Compressor(Effect):
    effect_type: Literal["Compressor"]
    def __init__(
        self,
        *,
        threshold: float = ...,
        ratio: float = ...,
        attack: float = ...,
        release: float = ...,
        knee: float = ...,
        gain: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class Expander(Effect):
    effect_type: Literal["Expander"]
    def __init__(
        self,
        *,
        threshold: float = ...,
        ratio: float = ...,
        attack: float = ...,
        release: float = ...,
        knee: float = ...,
        gain: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class Gate(Effect):
    effect_type: Literal["Gate"]
    def __init__(
        self,
        *,
        threshold: float = ...,
        ratio: float = ...,
        attack: float = ...,
        release: float = ...,
        knee: float = ...,
        gain: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class MultibandCompressor(Effect):
    effect_type: Literal["MultibandCompressor"]
    def __init__(
        self,
        *,
        frequency1: float = ...,
        frequency2: float = ...,
        frequency3: float = ...,
        frequency4: float = ...,
        threshold: tuple[float, float, float, float, float] = ...,
        ratio: tuple[float, float, float, float, float] = ...,
        attack: tuple[float, float, float, float, float] = ...,
        release: tuple[float, float, float, float, float] = ...,
        knee: tuple[float, float, float, float, float] = ...,
        gain: tuple[float, float, float, float, float] = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class MultibandExpander(Effect):
    effect_type: Literal["MultibandExpander"]
    def __init__(
        self,
        *,
        frequency1: float = ...,
        frequency2: float = ...,
        frequency3: float = ...,
        frequency4: float = ...,
        threshold: tuple[float, float, float, float, float] = ...,
        ratio: tuple[float, float, float, float, float] = ...,
        attack: tuple[float, float, float, float, float] = ...,
        release: tuple[float, float, float, float, float] = ...,
        knee: tuple[float, float, float, float, float] = ...,
        gain: tuple[float, float, float, float, float] = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class MultibandTransient(Effect):
    effect_type: Literal["MultibandTransient"]
    def __init__(
        self,
        *,
        frequency1: float = ...,
        frequency2: float = ...,
        fast_attack: tuple[float, float, float] = ...,
        fast_release: tuple[float, float, float] = ...,
        slow_attack: tuple[float, float, float] = ...,
        slow_release: tuple[float, float, float] = ...,
        transient_gain: tuple[float, float, float] = ...,
        sustain_gain: tuple[float, float, float] = ...,
        gain_smoothing: tuple[float, float, float] = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class PowerAmpSag(Effect):
    effect_type: Literal["PowerAmpSag"]
    def __init__(
        self,
        *,
        sag_sensitivity: float = ...,
        power_stability: int = ...,
        recovery_speed: int = ...,
        monoblock: bool = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class TransientShaper(Effect):
    effect_type: Literal["TransientShaper"]
    def __init__(
        self,
        *,
        fast_attack: float = ...,
        fast_release: float = ...,
        slow_attack: float = ...,
        slow_release: float = ...,
        transient_gain: float = ...,
        sustain_gain: float = ...,
        gain_smoothing: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class BandPassFilter(Effect):
    effect_type: Literal["BandPassFilter"]
    def __init__(
        self,
        *,
        high_pass_frequency: float = ...,
        low_pass_frequency: float = ...,
        high_pass_slope: int = ...,
        low_pass_slope: int = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class CombFilter(Effect):
    effect_type: Literal["CombFilter"]
    def __init__(
        self,
        *,
        fundamental_frequency: float = ...,
        feedback_gain: float = ...,
        dry_wet_mix: float = ...,
        comb_type: Literal["fb", "ff"] = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class EarphoneCableSim(Effect):
    effect_type: Literal["EarphoneCableSim"]
    def __init__(
        self,
        *,
        output_impedance: float = ...,
        cable_resistance: float = ...,
        cable_inductance: float = ...,
        voice_coil_inductance: float = ...,
        base_impedance: float = ...,
        resonance_frequency: tuple[float, float, float, float, float] = ...,
        resonance_q: tuple[float, float, float, float, float] = ...,
        resonance_impedance: tuple[float, float, float, float, float] = ...,
        resonance_enabled: tuple[bool, bool, bool, bool, bool] = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class FifteenBandGEQ(Effect):
    effect_type: Literal["FifteenBandGEQ"]
    def __init__(
        self,
        *,
        band_gain: tuple[float, float, float, float, float, float, float, float, float, float, float, float, float, float, float] = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class FifteenBandPEQ(Effect):
    effect_type: Literal["FifteenBandPEQ"]
    def __init__(
        self,
        *,
        frequencies: tuple[float, float, float, float, float, float, float, float, float, float, float, float, float, float, float] = ...,
        gains: tuple[float, float, float, float, float, float, float, float, float, float, float, float, float, float, float] = ...,
        q_values: tuple[float, float, float, float, float, float, float, float, float, float, float, float, float, float, float] = ...,
        filter_types: tuple[Literal["peaking", "lowPass", "highPass", "lowShelf", "highShelf", "bandPass", "notch", "allPass"], Literal["peaking", "lowPass", "highPass", "lowShelf", "highShelf", "bandPass", "notch", "allPass"], Literal["peaking", "lowPass", "highPass", "lowShelf", "highShelf", "bandPass", "notch", "allPass"], Literal["peaking", "lowPass", "highPass", "lowShelf", "highShelf", "bandPass", "notch", "allPass"], Literal["peaking", "lowPass", "highPass", "lowShelf", "highShelf", "bandPass", "notch", "allPass"], Literal["peaking", "lowPass", "highPass", "lowShelf", "highShelf", "bandPass", "notch", "allPass"], Literal["peaking", "lowPass", "highPass", "lowShelf", "highShelf", "bandPass", "notch", "allPass"], Literal["peaking", "lowPass", "highPass", "lowShelf", "highShelf", "bandPass", "notch", "allPass"], Literal["peaking", "lowPass", "highPass", "lowShelf", "highShelf", "bandPass", "notch", "allPass"], Literal["peaking", "lowPass", "highPass", "lowShelf", "highShelf", "bandPass", "notch", "allPass"], Literal["peaking", "lowPass", "highPass", "lowShelf", "highShelf", "bandPass", "notch", "allPass"], Literal["peaking", "lowPass", "highPass", "lowShelf", "highShelf", "bandPass", "notch", "allPass"], Literal["peaking", "lowPass", "highPass", "lowShelf", "highShelf", "bandPass", "notch", "allPass"], Literal["peaking", "lowPass", "highPass", "lowShelf", "highShelf", "bandPass", "notch", "allPass"], Literal["peaking", "lowPass", "highPass", "lowShelf", "highShelf", "bandPass", "notch", "allPass"]] = ...,
        enabled_bands: tuple[bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool] = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class FiveBandDynamicEQ(Effect):
    effect_type: Literal["FiveBandDynamicEQ"]
    def __init__(
        self,
        *,
        enabled_bands: tuple[bool, bool, bool, bool, bool] = ...,
        filter_type: tuple[Literal["pk", "ls", "hs"], Literal["pk", "ls", "hs"], Literal["pk", "ls", "hs"], Literal["pk", "ls", "hs"], Literal["pk", "ls", "hs"]] = ...,
        frequency: tuple[float, float, float, float, float] = ...,
        q: tuple[float, float, float, float, float] = ...,
        max_gain: tuple[float, float, float, float, float] = ...,
        threshold: tuple[float, float, float, float, float] = ...,
        ratio: tuple[float, float, float, float, float] = ...,
        knee: tuple[float, float, float, float, float] = ...,
        attack: tuple[float, float, float, float, float] = ...,
        release: tuple[float, float, float, float, float] = ...,
        sidechain_frequency: tuple[float, float, float, float, float] = ...,
        sidechain_q: tuple[float, float, float, float, float] = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class FiveBandFIRPEQ(Effect):
    effect_type: Literal["FiveBandFIRPEQ"]
    def __init__(
        self,
        *,
        latency_mode: Literal["0", "128", "256", "512", "1024"] = ...,
        filter_delay_samples: int = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
        assets: IRReverbAssets,
    ) -> None: ...

class FiveBandPEQ(Effect):
    effect_type: Literal["FiveBandPEQ"]
    def __init__(
        self,
        *,
        frequencies: tuple[float, float, float, float, float] = ...,
        gains: tuple[float, float, float, float, float] = ...,
        q_values: tuple[float, float, float, float, float] = ...,
        filter_types: tuple[Literal["peaking", "lowPass", "highPass", "lowShelf", "highShelf", "bandPass", "notch", "allPass"], Literal["peaking", "lowPass", "highPass", "lowShelf", "highShelf", "bandPass", "notch", "allPass"], Literal["peaking", "lowPass", "highPass", "lowShelf", "highShelf", "bandPass", "notch", "allPass"], Literal["peaking", "lowPass", "highPass", "lowShelf", "highShelf", "bandPass", "notch", "allPass"], Literal["peaking", "lowPass", "highPass", "lowShelf", "highShelf", "bandPass", "notch", "allPass"]] = ...,
        enabled_bands: tuple[bool, bool, bool, bool, bool] = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class GroupDelayEQ(Effect):
    effect_type: Literal["GroupDelayEQ"]
    def __init__(
        self,
        *,
        latency_mode: Literal["0", "128", "256", "512", "1024"] = ...,
        filter_delay_samples: int = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
        assets: IRReverbAssets,
    ) -> None: ...

class GroupDelayPEQ(Effect):
    effect_type: Literal["GroupDelayPEQ"]
    def __init__(
        self,
        *,
        latency_mode: Literal["0", "128", "256", "512", "1024"] = ...,
        filter_delay_samples: int = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
        assets: IRReverbAssets,
    ) -> None: ...

class HiPassFilter(Effect):
    effect_type: Literal["HiPassFilter"]
    def __init__(
        self,
        *,
        frequency: float = ...,
        slope: Literal[0, -12, -24, -36, -48, -60, -72, -84, -96] = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class LoPassFilter(Effect):
    effect_type: Literal["LoPassFilter"]
    def __init__(
        self,
        *,
        frequency: float = ...,
        slope: Literal[0, -12, -24, -36, -48, -60, -72, -84, -96] = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class LoudnessEqualizer(Effect):
    effect_type: Literal["LoudnessEqualizer"]
    def __init__(
        self,
        *,
        average_spl: float = ...,
        relative_volume: float = ...,
        low_gain: float = ...,
        low_frequency: int = ...,
        low_q: float = ...,
        high_q: float = ...,
        high_gain: float = ...,
        high_frequency: int = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class NarrowRange(Effect):
    effect_type: Literal["NarrowRange"]
    def __init__(
        self,
        *,
        high_pass_frequency: float = ...,
        high_pass_slope: int = ...,
        low_pass_frequency: float = ...,
        low_pass_slope: int = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class RoomEQ(Effect):
    effect_type: Literal["RoomEQ"]
    def __init__(
        self,
        *,
        latency_mode: Literal["0", "128", "256", "512", "1024"] = ...,
        filter_delay_samples: int = ...,
        channel_delay: int = ...,
        output_gain: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
        assets: IRReverbAssets,
    ) -> None: ...

class TiltEQ(Effect):
    effect_type: Literal["TiltEQ"]
    def __init__(
        self,
        *,
        pivot_frequency: float = ...,
        slope: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class TonalBalanceEQ(Effect):
    effect_type: Literal["TonalBalanceEQ"]
    def __init__(
        self,
        *,
        target: Literal["All", "Classical", "Electronic", "Pop", "Rock", "Tilt"] = ...,
        amount: float = ...,
        range: float = ...,
        smoothing: float = ...,
        averaging_time: float = ...,
        low: float = ...,
        high: float = ...,
        average_spl: float = ...,
        adjust_enabled: tuple[bool, bool, bool, bool, bool] = ...,
        adjust_type: tuple[Literal["pk", "ls", "hs"], Literal["pk", "ls", "hs"], Literal["pk", "ls", "hs"], Literal["pk", "ls", "hs"], Literal["pk", "ls", "hs"]] = ...,
        adjust_frequency: tuple[float, float, float, float, float] = ...,
        adjust_gain: tuple[float, float, float, float, float] = ...,
        adjust_q: tuple[float, float, float, float, float] = ...,
        tilt_slope: float = ...,
        tilt_corner: float = ...,
        measurement_paused: bool = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class ToneControl(Effect):
    effect_type: Literal["ToneControl"]
    def __init__(
        self,
        *,
        bass: float = ...,
        mid: float = ...,
        treble: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class AMRadioSimulator(Effect):
    effect_type: Literal["AMRadioSimulator"]
    def __init__(
        self,
        *,
        radio: bool = ...,
        tx_bandwidth: float = ...,
        pre_emphasis: float = ...,
        mod_depth: float = ...,
        compression: float = ...,
        stereo_mode: Literal["Mono", "C-QUAM"] = ...,
        signal: float = ...,
        skywave: float = ...,
        fading_speed: float = ...,
        static_rate: float = ...,
        interference: float = ...,
        interference_offset: float = ...,
        tuning: float = ...,
        if_bandwidth: float = ...,
        agc_speed: Literal["Slow", "Mid", "Fast"] = ...,
        detector_rc: float = ...,
        hum: float = ...,
        hum_frequency: Literal["50", "60"] = ...,
        speaker: Literal["Off", "Small", "Table"] = ...,
        output_gain: float = ...,
        mix: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class BitCrusher(Effect):
    effect_type: Literal["BitCrusher"]
    def __init__(
        self,
        *,
        bit_depth: int = ...,
        tpdf_dither: bool = ...,
        zoh_frequency: float = ...,
        bit_error: float = ...,
        seed: int = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class BluetoothSBCSimulator(Effect):
    effect_type: Literal["BluetoothSBCSimulator"]
    def __init__(
        self,
        *,
        bitpool: int = ...,
        channel_mode: Literal["Joint Stereo", "Stereo", "Dual Channel"] = ...,
        blocks: Literal["4", "8", "12", "16"] = ...,
        output_gain: float = ...,
        mix: float = ...,
        packet_loss: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class CassetteArtifacts(Effect):
    effect_type: Literal["CassetteArtifacts"]
    def __init__(
        self,
        *,
        deck_grade: Literal["Reference", "Hi-Fi", "Consumer", "Portable"] = ...,
        tape_type: Literal["Type I", "Type II", "Type IV"] = ...,
        noise_reduction: Literal["Off", "Dolby B", "Dolby C"] = ...,
        bias: float = ...,
        record_level: float = ...,
        wow_flutter: float = ...,
        hiss: float = ...,
        dropouts: float = ...,
        azimuth: float = ...,
        dolby_level_error: float = ...,
        output: float = ...,
        mix: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class DigitalErrorEmulator(Effect):
    effect_type: Literal["DigitalErrorEmulator"]
    def __init__(
        self,
        *,
        bit_error_rate: float = ...,
        mode: Literal["1", "2A", "2B", "3A", "3B", "4", "5A", "5B", "5C", "6A", "6B", "8", "9", "10", "10A"] = ...,
        reference_sample_rate: float = ...,
        wet_mix: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class DSD64IMDSimulator(Effect):
    effect_type: Literal["DSD64IMDSimulator"]
    def __init__(
        self,
        *,
        amount: float = ...,
        dry_wet: int = ...,
        ultrasonic_level: float = ...,
        noise_color: int = ...,
        analog_nonlinearity: float = ...,
        even_bias: int = ...,
        signal_coupling: int = ...,
        scratch_tone: float = ...,
        noise_texture: int = ...,
        cross_sideband: int = ...,
        imd_path_hpf: float = ...,
        output_trim: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class FMRadioSimulator(Effect):
    effect_type: Literal["FMRadioSimulator"]
    def __init__(
        self,
        *,
        radio: bool = ...,
        emphasis: Literal["50us", "75us"] = ...,
        processing: float = ...,
        signal: float = ...,
        tuning: float = ...,
        if_bandwidth: float = ...,
        multipath: float = ...,
        path_delay: float = ...,
        fading: float = ...,
        stereo: Literal["Auto", "Stereo", "Mono"] = ...,
        output_gain: float = ...,
        mix: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class G726ADPCMSimulator(Effect):
    effect_type: Literal["G726ADPCMSimulator"]
    def __init__(
        self,
        *,
        bitrate: Literal["16", "24", "32", "40"] = ...,
        output_gain: float = ...,
        mix: int = ...,
        radio_bit_error_rate: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class GSMFullRateSimulator(Effect):
    effect_type: Literal["GSMFullRateSimulator"]
    def __init__(
        self,
        *,
        transcodes: int = ...,
        output_gain: float = ...,
        mix: int = ...,
        carrier_to_interference: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class HumGenerator(Effect):
    effect_type: Literal["HumGenerator"]
    def __init__(
        self,
        *,
        frequency: float = ...,
        hum_type: Literal["Standard", "Rich", "Dirty"] = ...,
        harmonics: int = ...,
        tone: float = ...,
        instability: float = ...,
        level: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class MDSimulator(Effect):
    effect_type: Literal["MDSimulator"]
    def __init__(
        self,
        *,
        mode: Literal["SP (292 kbps)", "LP2 (132 kbps)", "LP4 (66 kbps)"] = ...,
        output_gain: float = ...,
        mix: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class MP3CodecSimulator(Effect):
    effect_type: Literal["MP3CodecSimulator"]
    def __init__(
        self,
        *,
        codec_rate: Literal["22.05 kHz (MPEG-2)", "44.1 kHz (MPEG-1)"] = ...,
        bitrate: Literal["32", "48", "64", "80", "96", "112", "128", "160", "192", "224", "256", "320"] = ...,
        stereo_mode: Literal["Joint Stereo", "Stereo"] = ...,
        bit_reservoir: bool = ...,
        output_gain: float = ...,
        mix: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class NoiseBlender(Effect):
    effect_type: Literal["NoiseBlender"]
    def __init__(
        self,
        *,
        noise_type: Literal["white", "pink", "brown"] = ...,
        level: float = ...,
        per_channel: bool = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class SimpleJitter(Effect):
    effect_type: Literal["SimpleJitter"]
    def __init__(
        self,
        *,
        rms_jitter_nanoseconds: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class SWRadioSimulator(Effect):
    effect_type: Literal["SWRadioSimulator"]
    def __init__(
        self,
        *,
        radio: bool = ...,
        tx_bandwidth: float = ...,
        pre_emphasis: float = ...,
        mod_depth: float = ...,
        compression: float = ...,
        signal: float = ...,
        skywave: float = ...,
        fading_speed: float = ...,
        delay_spread: float = ...,
        static_rate: float = ...,
        interference: float = ...,
        interference_offset: float = ...,
        tuning: float = ...,
        if_bandwidth: float = ...,
        detector: Literal["Envelope", "Synchronous"] = ...,
        agc_speed: Literal["Slow", "Mid", "Fast"] = ...,
        detector_rc: float = ...,
        hum: float = ...,
        hum_frequency: Literal["50", "60"] = ...,
        speaker: Literal["Off", "Small", "Table"] = ...,
        output_gain: float = ...,
        mix: float = ...,
        mode: Literal["AM", "USB", "LSB"] = ...,
        bfo_offset: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class TapeArtifacts(Effect):
    effect_type: Literal["TapeArtifacts"]
    def __init__(
        self,
        *,
        speed: Literal["7.5", "15", "30"] = ...,
        tape: Literal["Standard", "Master"] = ...,
        bias: float = ...,
        record_level: float = ...,
        wow_flutter: float = ...,
        hiss: float = ...,
        output: float = ...,
        mix: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class TVAudioSimulator(Effect):
    effect_type: Literal["TVAudioSimulator"]
    def __init__(
        self,
        *,
        broadcast: bool = ...,
        standard: Literal["M/EIA-J", "M/BTSC", "M/A2", "B/G A2", "B/G NICAM", "I NICAM", "D/K Mono", "L AM"] = ...,
        tx_mode: Literal["Stereo", "Mono", "Dual"] = ...,
        processing: float = ...,
        signal: float = ...,
        tuning: float = ...,
        if_bandwidth: float = ...,
        multipath: float = ...,
        path_delay: float = ...,
        fading: float = ...,
        receive_mode: Literal["Auto", "Stereo", "Main", "Sub"] = ...,
        buzz: float = ...,
        output_gain: float = ...,
        mix: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class VinylArtifacts(Effect):
    effect_type: Literal["VinylArtifacts"]
    def __init__(
        self,
        *,
        pops_per_minute: int = ...,
        pop_level: float = ...,
        crackles_per_minute: int = ...,
        crackle_level: float = ...,
        hiss_level: float = ...,
        rumble_level: float = ...,
        crosstalk: int = ...,
        noise_profile: float = ...,
        wear: int = ...,
        react: int = ...,
        react_mode: Literal["Velocity", "Amplitude"] = ...,
        mix: int = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class VinylSimulator(Effect):
    effect_type: Literal["VinylSimulator"]
    def __init__(
        self,
        *,
        cut_level: float = ...,
        high_frequency_cutoff: float = ...,
        bass_mono_below: float = ...,
        side_mix: float = ...,
        speed: Literal["33⅓", "45", "78"] = ...,
        radius: float = ...,
        roughness: float = ...,
        dust_rate: float = ...,
        static_rate: float = ...,
        scratch_rate: float = ...,
        stylus_shape: Literal["Spherical", "Elliptical"] = ...,
        side_radius: float = ...,
        scan_radius: float = ...,
        tracking_force: float = ...,
        tip_mass: float = ...,
        compliance: float = ...,
        damping: float = ...,
        quality: Literal["Eco", "Standard", "High", "Ultra"] = ...,
        output_gain: float = ...,
        mix: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class AutoFilter(Effect):
    effect_type: Literal["AutoFilter"]
    def __init__(
        self,
        *,
        mode: Literal["LFO", "Envelope"] = ...,
        filter_type: Literal["Low-pass", "Band-pass", "High-pass"] = ...,
        minimum_frequency: float = ...,
        maximum_frequency: float = ...,
        resonance: float = ...,
        mix: float = ...,
        rate: float = ...,
        waveform: Literal["Sine", "Triangle"] = ...,
        stereo_phase: float = ...,
        sensitivity: float = ...,
        attack: float = ...,
        release: float = ...,
        direction: Literal["Up", "Down"] = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class AutoPan(Effect):
    effect_type: Literal["AutoPan"]
    def __init__(
        self,
        *,
        rate: float = ...,
        depth: float = ...,
        center: float = ...,
        width: float = ...,
        waveform: Literal["Sine", "Triangle"] = ...,
        phase: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class Chorus(Effect):
    effect_type: Literal["Chorus"]
    def __init__(
        self,
        *,
        mode: Literal["Chorus", "Stereo Chorus", "Ensemble", "Flanger", "Vibrato"] = ...,
        rate: float = ...,
        delay: float = ...,
        depth: float = ...,
        voices: int = ...,
        stereo_spread: float = ...,
        feedback: float = ...,
        mix: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class DopplerDistortion(Effect):
    effect_type: Literal["DopplerDistortion"]
    def __init__(
        self,
        *,
        coil_force: float = ...,
        speaker_mass: float = ...,
        spring_constant: float = ...,
        damping_factor: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class FrequencyShifter(Effect):
    effect_type: Literal["FrequencyShifter"]
    def __init__(
        self,
        *,
        mode: Literal["Shift", "Ring Mod", "Barber-pole"] = ...,
        shift: float = ...,
        carrier_frequency: float = ...,
        minimum_shift: float = ...,
        maximum_shift: float = ...,
        rate: float = ...,
        direction: Literal["Up", "Down"] = ...,
        stereo_phase: float = ...,
        mix: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class Phaser(Effect):
    effect_type: Literal["Phaser"]
    def __init__(
        self,
        *,
        mode: Literal["Classic", "Barber-pole"] = ...,
        rate: float = ...,
        center_frequency: float = ...,
        range: float = ...,
        stages: Literal[2, 4, 6, 8, 10, 12] = ...,
        feedback: float = ...,
        stereo_phase: float = ...,
        direction: Literal["Up", "Down"] = ...,
        mix: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class PitchShifter(Effect):
    effect_type: Literal["PitchShifter"]
    def __init__(
        self,
        *,
        pitch_shift: int = ...,
        fine_tune: int = ...,
        window_size: int = ...,
        crossfade_time: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class PitchShifterHQ(Effect):
    effect_type: Literal["PitchShifterHQ"]
    def __init__(
        self,
        *,
        pitch_shift: int = ...,
        fine_tune: int = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class RotarySpeaker(Effect):
    effect_type: Literal["RotarySpeaker"]
    def __init__(
        self,
        *,
        speed_state: Literal["Stop", "Slow", "Fast"] = ...,
        speed: float = ...,
        acceleration: float = ...,
        crossover: float = ...,
        rotor_balance: float = ...,
        stereo_width: float = ...,
        doppler_depth: float = ...,
        amplitude_depth: float = ...,
        mix: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class Tremolo(Effect):
    effect_type: Literal["Tremolo"]
    def __init__(
        self,
        *,
        rate: float = ...,
        depth: float = ...,
        randomness: float = ...,
        randomness_cutoff: float = ...,
        randomness_slope: float = ...,
        channel_phase: float = ...,
        channel_sync: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class WowFlutter(Effect):
    effect_type: Literal["WowFlutter"]
    def __init__(
        self,
        *,
        rate: float = ...,
        depth: float = ...,
        randomness: float = ...,
        randomness_cutoff: float = ...,
        randomness_slope: float = ...,
        channel_phase: float = ...,
        channel_sync: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class Oscillator(Effect):
    effect_type: Literal["Oscillator"]
    def __init__(
        self,
        *,
        frequency: float = ...,
        volume: float = ...,
        panning: float = ...,
        waveform: Literal["sine", "square", "triangle", "sawtooth", "white", "pink", "impulse"] = ...,
        mode: Literal["continuous", "pulsed"] = ...,
        interval: float = ...,
        width: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class HornResonator(Effect):
    effect_type: Literal["HornResonator"]
    def __init__(
        self,
        *,
        crossover: float = ...,
        length: float = ...,
        throat_diameter: float = ...,
        mouth_diameter: float = ...,
        curve: float = ...,
        damping: float = ...,
        throat_reflection: float = ...,
        waveguide_gain: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class HornResonatorPlus(Effect):
    effect_type: Literal["HornResonatorPlus"]
    def __init__(
        self,
        *,
        crossover: float = ...,
        length: float = ...,
        throat_diameter: float = ...,
        mouth_diameter: float = ...,
        curve: float = ...,
        damping: float = ...,
        throat_reflection: float = ...,
        waveguide_gain: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class ModalResonator(Effect):
    effect_type: Literal["ModalResonator"]
    def __init__(
        self,
        *,
        resonator_enabled: tuple[bool, bool, bool, bool, bool] = ...,
        frequency_log: tuple[float, float, float, float, float] = ...,
        decay: tuple[float, float, float, float, float] = ...,
        low_pass_log: tuple[float, float, float, float, float] = ...,
        high_pass_log: tuple[float, float, float, float, float] = ...,
        gain: tuple[float, float, float, float, float] = ...,
        mix: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class ClickRemover(Effect):
    effect_type: Literal["ClickRemover"]
    def __init__(
        self,
        *,
        sensitivity: float = ...,
        max_repair_length: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class ClipRestorer(Effect):
    effect_type: Literal["ClipRestorer"]
    def __init__(
        self,
        *,
        threshold: float = ...,
        output_gain: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class HumRemover(Effect):
    effect_type: Literal["HumRemover"]
    def __init__(
        self,
        *,
        frequency: Literal["Auto", "50 Hz", "60 Hz"] = ...,
        harmonics: int = ...,
        tracking_speed: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class NoiseReduction(Effect):
    effect_type: Literal["NoiseReduction"]
    def __init__(
        self,
        *,
        reduction: float = ...,
        sensitivity: float = ...,
        smoothing: float = ...,
        treble_care: float = ...,
        mix: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class DattorroPlateReverb(Effect):
    effect_type: Literal["DattorroPlateReverb"]
    def __init__(
        self,
        *,
        pre_delay: float = ...,
        bandwidth: float = ...,
        input_diffusion1: float = ...,
        input_diffusion2: float = ...,
        decay: float = ...,
        decay_diffusion1: float = ...,
        damping: float = ...,
        modulation_depth: float = ...,
        modulation_rate: float = ...,
        wet_mix: int = ...,
        dry_mix: int = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class FDNReverb(Effect):
    effect_type: Literal["FDNReverb"]
    def __init__(
        self,
        *,
        reverb_time: float = ...,
        density: int = ...,
        pre_delay: float = ...,
        base_delay: float = ...,
        delay_spread: float = ...,
        high_frequency_damp: float = ...,
        low_cut: int = ...,
        modulation_depth: float = ...,
        modulation_rate: float = ...,
        diffusion: int = ...,
        wet_mix: int = ...,
        dry_mix: int = ...,
        stereo_width: int = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class IRReverb(Effect):
    effect_type: Literal["IRReverb"]
    def __init__(
        self,
        *,
        channel_mode: Literal["automatic", "mono", "independent", "trueStereo", "matrix"] = ...,
        latency: Literal[0, 128, 256, 512, 1024] = ...,
        convolution_rate: Literal["auto", "full", "half", "quarter"] = ...,
        wet_level: float = ...,
        dry_enabled: bool = ...,
        dry_level: float = ...,
        pre_delay: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
        assets: IRReverbAssets,
    ) -> None: ...

class RSReverb(Effect):
    effect_type: Literal["RSReverb"]
    def __init__(
        self,
        *,
        pre_delay: float = ...,
        room_size: float = ...,
        reverb_time: float = ...,
        density: int = ...,
        diffusion: float = ...,
        damping: int = ...,
        high_damp: int = ...,
        low_damp: int = ...,
        mix: int = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class BandwidthExtender(Effect):
    effect_type: Literal["BandwidthExtender"]
    def __init__(
        self,
        *,
        harmonic_amount: float = ...,
        noise_amount: float = ...,
        cutoff_mode: Literal["Auto", "Manual"] = ...,
        cutoff_frequency: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class BassExtender(Effect):
    effect_type: Literal["BassExtender"]
    def __init__(
        self,
        *,
        amount: float = ...,
        output_gain: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class DynamicSaturation(Effect):
    effect_type: Literal["DynamicSaturation"]
    def __init__(
        self,
        *,
        speaker_drive: float = ...,
        speaker_stiffness: float = ...,
        speaker_damping: float = ...,
        speaker_mass: float = ...,
        distortion_drive: float = ...,
        distortion_bias: float = ...,
        distortion_mix: float = ...,
        cone_motion_mix: float = ...,
        output_gain: float = ...,
        oversampling: Literal[1, 2, 4, 8] = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class Exciter(Effect):
    effect_type: Literal["Exciter"]
    def __init__(
        self,
        *,
        high_pass_frequency: float = ...,
        high_pass_slope: Literal[0, 6, 12] = ...,
        drive: float = ...,
        bias: float = ...,
        mix: float = ...,
        oversampling: Literal[1, 2, 4, 8] = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class HardClipping(Effect):
    effect_type: Literal["HardClipping"]
    def __init__(
        self,
        *,
        threshold: float = ...,
        mode: Literal["both", "positive", "negative"] = ...,
        oversampling: Literal[1, 2, 4, 8, 16] = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class HarmonicDistortion(Effect):
    effect_type: Literal["HarmonicDistortion"]
    def __init__(
        self,
        *,
        second_harmonic: float = ...,
        third_harmonic: float = ...,
        fourth_harmonic: float = ...,
        fifth_harmonic: float = ...,
        sensitivity: float = ...,
        oversampling: Literal[1, 2, 4, 8] = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class MultibandSaturation(Effect):
    effect_type: Literal["MultibandSaturation"]
    def __init__(
        self,
        *,
        frequency1: float = ...,
        frequency2: float = ...,
        drive: tuple[float, float, float] = ...,
        bias: tuple[float, float, float] = ...,
        mix: tuple[float, float, float] = ...,
        gain: tuple[float, float, float] = ...,
        oversampling: Literal[1, 2, 4, 8] = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class Saturation(Effect):
    effect_type: Literal["Saturation"]
    def __init__(
        self,
        *,
        drive: float = ...,
        bias: float = ...,
        mix: float = ...,
        gain: float = ...,
        oversampling: Literal[1, 2, 4, 8] = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class SubSynth(Effect):
    effect_type: Literal["SubSynth"]
    def __init__(
        self,
        *,
        sub_level: float = ...,
        dry_level: float = ...,
        sub_low_pass_frequency: float = ...,
        sub_low_pass_slope: int = ...,
        sub_high_pass_frequency: float = ...,
        sub_high_pass_slope: int = ...,
        dry_high_pass_frequency: float = ...,
        dry_high_pass_slope: int = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class TubeSimulator(Effect):
    effect_type: Literal["TubeSimulator"]
    def __init__(
        self,
        *,
        input_volume: float = ...,
        tube: Literal["12AX7", "12AT7", "12AU7", "Bypass"] = ...,
        bias: float = ...,
        plate_voltage: float = ...,
        source_impedance: float = ...,
        supply_impedance: float = ...,
        output_trim: float = ...,
        mix: float = ...,
        input_reference: float = ...,
        negative_feedback: float = ...,
        output_stage: Literal["Line", "Power", "SingleEnded"] = ...,
        power_tube: Literal["EL84", "EL34", "6L6GC", "KT88"] = ...,
        power_bplus: float = ...,
        cathode_resistor: float = ...,
        screen_tap: Literal["0", "20", "43"] = ...,
        primary_impedance: Literal["6.0", "6.6", "8.0"] = ...,
        speaker_load: Literal["4", "8", "15", "16"] = ...,
        actual_speaker_load: float = ...,
        safety_trim: float = ...,
        auto_gain_reduction: bool = ...,
        se_tube: Literal["300B", "2A3"] = ...,
        se_bplus: float = ...,
        se_cathode_resistor: float = ...,
        se_primary_impedance: Literal["2.5", "3.5", "5.0"] = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class CrossfeedFilter(Effect):
    effect_type: Literal["CrossfeedFilter"]
    def __init__(
        self,
        *,
        level: float = ...,
        delay: float = ...,
        low_pass_frequency: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class CrosstalkCancellation(Effect):
    effect_type: Literal["CrosstalkCancellation"]
    def __init__(
        self,
        *,
        latency_mode: Literal["0", "128", "256", "512", "1024"] = ...,
        filter_delay_samples: int = ...,
        strength: float = ...,
        output_gain: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
        assets: IRReverbAssets,
    ) -> None: ...

class MSMatrix(Effect):
    effect_type: Literal["MSMatrix"]
    def __init__(
        self,
        *,
        mode: int = ...,
        mid_gain: float = ...,
        side_gain: float = ...,
        swap: int = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class MultibandBalance(Effect):
    effect_type: Literal["MultibandBalance"]
    def __init__(
        self,
        *,
        frequency1: float = ...,
        frequency2: float = ...,
        frequency3: float = ...,
        frequency4: float = ...,
        balance: tuple[float, float, float, float, float] = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class PhaseSelectEQ(Effect):
    effect_type: Literal["PhaseSelectEQ"]
    def __init__(
        self,
        *,
        region_enabled: tuple[bool, bool, bool, bool, bool] = ...,
        outer_frequency_low: tuple[float, float, float, float, float] = ...,
        core_frequency_low: tuple[float, float, float, float, float] = ...,
        core_frequency_high: tuple[float, float, float, float, float] = ...,
        outer_frequency_high: tuple[float, float, float, float, float] = ...,
        outer_phase_low: tuple[float, float, float, float, float] = ...,
        core_phase_low: tuple[float, float, float, float, float] = ...,
        core_phase_high: tuple[float, float, float, float, float] = ...,
        outer_phase_high: tuple[float, float, float, float, float] = ...,
        gain: tuple[float, float, float, float, float] = ...,
        region_solo: tuple[bool, bool, bool, bool, bool] = ...,
        outer_balance_low: tuple[float, float, float, float, float] = ...,
        core_balance_low: tuple[float, float, float, float, float] = ...,
        core_balance_high: tuple[float, float, float, float, float] = ...,
        outer_balance_high: tuple[float, float, float, float, float] = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class SpatialMapper(Effect):
    effect_type: Literal["SpatialMapper"]
    def __init__(
        self,
        *,
        input_channels: int = ...,
        bands: Literal["8", "16", "24", "32", "48"] = ...,
        directness: float = ...,
        separation: float = ...,
        diffuse_extraction: float = ...,
        phase_sensitivity: float = ...,
        temporal_smoothing: float = ...,
        energy_preservation: bool = ...,
        direct_matrix: tuple[float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float] = ...,
        diffuse_matrix: tuple[float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float] = ...,
        residual_matrix: tuple[float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float] = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

class StereoBlend(Effect):
    effect_type: Literal["StereoBlend"]
    def __init__(
        self,
        *,
        stereo: float = ...,
        id: str | None = ...,
        enabled: bool = ...,
        channel: EffectChannel = ...,
    ) -> None: ...

EFFECT_CLASSES: dict[str, type[Effect]]
def create_effect(effect_type: str, **options: object) -> Effect: ...

__all__: list[str]
